# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForeginModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '外键测试表',
                'verbose_name_plural': '外键测试表',
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '测试model',
                'verbose_name_plural': '测试model',
            },
        ),
        migrations.AddField(
            model_name='foreginmodel',
            name='test_m',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.TestModel', verbose_name='外键表'),
        ),
    ]
